
//---- Auth ----
export const AUTH = {
  FETCH_AUTH_CREDENTIALS: 'FETCH_AUTH_CREDENTIALS',
  FETCH_AUTH_CREDENTIALS_SUCCESS: 'FETCH_AUTH_CREDENTIALS_SUCCESS',
  FETCH_AUTH_CREDENTIALS_FAIL: 'FETCH_AUTH_CREDENTIALS_FAIL',
  FETCH_AUTH_ROLES: 'FETCH_AUTH_ROLES',
  FETCH_AUTH_ROLES_SUCCESS: 'FETCH_AUTH_ROLES_SUCCESS',
  FETCH_AUTH_ROLES_FAIL: 'FETCH_AUTH_ROLES_FAIL',
  SET_ADMIN_DATA: 'SET_ADMIN_DATA',
}

//---- Clients ----
export const CLIENTS = {
  FETCH_CLIENTS: 'FETCH_CLIENTS',
  FETCH_CLIENTS_SUCCESS: 'FETCH_CLIENTS_SUCCESS',
  FETCH_CLIENTS_FAIL: 'FETCH_CLIENTS_FAIL',
  
  FETCH_CLIENT: 'FETCH_CLIENT',
  FETCH_CLIENT_SUCCESS: 'FETCH_CLIENT_SUCCESS',
  FETCH_CLIENT_FAIL: 'FETCH_CLIENT_FAIL',
  
  CREATE_CLIENT: 'CREATE_CLIENT',
  CREATE_CLIENT_SUCCESS: 'CREATE_CLIENT_SUCCESS',
  CREATE_CLIENT_FAIL: 'CREATE_CLIENT_FAIL',
  
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  UPDATE_CLIENT_SUCCESS: 'UPDATE_CLIENT_SUCCESS',
  UPDATE_CLIENT_FAIL: 'UPDATE_CLIENT_FAIL',
  
  DELETE_CLIENT: 'DELETE_CLIENT',
  DELETE_CLIENT_SUCCESS: 'DELETE_CLIENT_SUCCESS',
  DELETE_CLIENT_FAIL: 'DELETE_CLIENT_FAIL',
}

//---- Modal ----
export const MODAL = {
  TOGGLE_MODAL: 'TOGGLE_MODAL'
}

//---- Modal ----
export const APP = {
  TOGGLE_NAV_OVERLAY: 'TOGGLE_NAV_OVERLAY',
  SET_NAV_REGION: 'SET_NAV_REGION',
  SET_NAV_COUNTRY: 'SET_NAV_COUNTRY',
}