apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: default
  labels:
    service: boilerplate
  name: boilerplate
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    service: boilerplate
status:
  loadBalancer: {}
